export const APP_PATHS = {
  login: "/",
  register: "/register",
  dashboard: "/dashboard",
  myFiles: "/my-files",
  uploadFile: "/upload",
  searchFiles: "/search",
  activityLogs: "/dashboard/activity-logs",
  storageHealth: "/storage-health",
  sharedWithMe: "/shared-with-me",
  sharedByMe: "/shared-by-me",
  storageAnalytics: "/storage-analytics",
  failoverHistory: "/failover-history",
  profile: "/profile",
  architecture: "/architecture",
};
